# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NPM Package

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
      dry-run:
        type: boolean
        default: false
        required: false

jobs:
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        if: ${{ !inputs.dry-run }}
        with:
          ref: ${{ inputs.tag }}
      - uses: actions/checkout@v5
        if: ${{ inputs.dry-run }}
        with:
          ref: ${{ github.ref_name || github.ref }}
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          registry-url: https://registry.npmjs.org/
      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          DRY_RUN: ${{ inputs.dry-run || false }}
        run: |
          yarn install
          yarn build
          npm whoami
          npm config ls -l
          if [[ "$DRY_RUN" = true ]]
          then
            npm publish --dry-run
          else
            npm publish
          fi

  publish-github:
    name: Publish to GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
        if: ${{ !inputs.dry-run }}
        with:
          ref: ${{ inputs.tag }}
      - uses: actions/checkout@v5
        if: ${{ inputs.dry-run }}
        with:
          ref: ${{ github.ref_name || github.ref }}
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          registry-url: https://npm.pkg.github.com
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: ${{ inputs.dry-run || false }}
        run: |
          yarn install
          yarn build
          yarn registry:github
          npm config ls -l
          if [[ "$DRY_RUN" = true ]]
          then
            npm publish --dry-run
          else
            npm publish
          fi
